### ISSUE TITLE
I do not even get syntax highlighting

### ISSUE THREAD

**Issue by hbr** [edwinb/idris2-vim#23]
I have done exactly the steps

    cd ~/.vim/bundle
    git clone https://github.com/edwinb/idris2-vim.git

But after opening some idris file, I do not even get syntax highlighting.

Note: I do not understand what you meant by *recommend use of pathogen*.

Maybe additional steps have to be done.

**Comment by buzden** [comment]
<details>
<summary>I personally don't use pathogen because I have idris2-vim plugin installed directly, so I may be wrong.</summary>

```
/usr/share/vim/vimfiles/after/ftplugin/idris2.vim
/usr/share/vim/vimfiles/after/syntax/idris2.vim
/usr/share/vim/vimfiles/ftdetect/idris2.vim
/usr/share/vim/vimfiles/ftdetect/lidris2.vim
/usr/share/vim/vimfiles/ftplugin/idris2.vim
/usr/share/vim/vimfiles/indent/idris2.vim
/usr/share/vim/vimfiles/syntax/idris2.vim
/usr/share/vim/vimfiles/syntax/lidris2.vim
/usr/share/vim/vimfiles/syntax_checkers/idris2/idris2.vim
```
</details>

But as far as I remember, when you are using the [pathogen plugin](https://github.com/tpope/vim-pathogen), you have to enable it explicitly in your `.vimrc`, so just unpacking to bundles dir is not enough.

**Comment by hbr** [comment]
I don’t use pathogen either. What is the way to install the plugin directly?

**Comment by hbr** [comment]
I have installed pathogen (which is really trivial). Now syntax highlighting works. Forget the previous comment.

Thanks for your hint.
